site_name: Preguntonic
nav:
  - Home: index.md
  - Arquitectura: arquitectura.md
  - Acuerdo Interfaces: acuerdo-interfaces.md
  - ¿Cómo jugar?: como-jugar.md

theme:
  name: mkdocs
  locale: es
  color_mode: auto
  user_color_mode_toggle: true
