site_name: Preguntonic
nav:
  - Home: index.md
  - Desarrollo: desarrollo.md
  - Arquitectura: arquitectura.md
  - Diagramas: diagramas.md
  - Base de datos: base-datos.md
  - Acuerdo Interfaces: acuerdo-interfaces.md

theme:
  name: mkdocs
  locale: es
  color_mode: auto
  user_color_mode_toggle: true
